name: rgi
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >= 3.5
  - pip
  - biopython 1.78
  - filetype >= 1.0.0
  - pytest >= 3.0.0
  - pandas >= 0.15.0
  - matplotlib >= 2.1.2
  - seaborn >= 0.8.1
  - pyfaidx >= 0.5.4.1
  - pyahocorasick 1.4.0
  - beautifulsoup4 4.9.3
  - requests 2.24.0
  - lxml 4.6.1
  - zlib
  - dask
  - pip:
    - diamond==0.8.36
    - blast==2.14.1
    - prodigal==2.6.3
    - bamtools==2.5.1
    - bowtie2[version='>=2.3.4.3']
    - bwa[version='>=0.7.17']
    - kma[version='>=1.2.26s']
    - pyrodigal[version='>=3.0.0']
    - samtools==1.9
    - pysam==0.16.0.1
    - oligoarrayaux==3.8
    - bedtools[version='>=2.28.0']
    - bioconda::jellyfish
